# Generated by Django 6.1.2 on 2026-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentfigure',
            name='scope',
            field=models.CharField(choices=[('PROJECT', 'This project in Palghar district'), ('WIDER', 'Wider project / corridor beyond Palghar')], default='PROJECT', help_text='WIDER when the figure covers a corridor/project extending beyond Palghar district', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='headline_investment_scope',
            field=models.CharField(blank=True, choices=[('PROJECT', 'This project in Palghar district'), ('WIDER', 'Wider project / corridor beyond Palghar')], max_length=8),
        ),
    ]
